name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./FlashLFQ.sln
    - name: Build (CMD)
      run: dotnet publish /p:Configuration=Release ./CMD/CMD.csproj  -f net8.0
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --tag smithchemwisc/flashlfq:dev .
    - name: Upload the docker image
      run: |
        docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push smithchemwisc/flashlfq:dev
      
      
